export const columnsVisible = [
  "user_email",
  "user_date",
  "region_name",
  "address",
  "dateopen",
  "dateclose",
  "area",
  "kolbakers",
  "description",
  "territory_name",
];
export const columns = [
  {
    name: "name",
    label: "Наименование",
    align: "left",
    field: "name",
    required: true,
    sortable: true,
  },
  {
    name: "territory_name",
    label: "Территория",
    align: "left",
    field: "territory_name",
    required: true,
    sortable: true,
  },
  {
    name: "region_name",
    label: "Регион",
    align: "left",
    field: "region_name",
    required: true,
    sortable: true,
  },
  {
    name: "franch",
    label: "Фрч",
    align: "left",
    field: "franch",
    required: true,
  },
  {
    name: "date_start",
    label: "старт",
    align: "left",
    field: "date_start",
    required: true,
  },
  {
    name: "date_end",
    label: "end",
    align: "left",
    field: "date_end",
    required: true,
  },
  {
    name: "trdemark_name",
    label: "Торг.сеть",
    align: "left",
    field: "trdemark_name",
  },

  {
    name: "city_name",
    label: "Город",
    align: "left",
    field: "city_name",
  },
  {
    name: "address",
    label: "Адрес",
    align: "left",
    field: "address",
  },
  {
    name: "dateopen",
    label: "Открыто",
    align: "left",
    field: "dateopen",
  },
  {
    name: "dateclose",
    label: "Закрыто",
    align: "left",
    field: "dateclose",
  },
  {
    name: "area",
    label: "Площадь",
    align: "left",
    field: "area",
  },
  {
    name: "kolbakers",
    label: "Кол.пекарей",
    align: "left",
    field: "kolbakers",
  },
  {
    name: "ispack",
    label: "Упаковка",
    align: "left",
    field: "ispack",
  },
  {
    name: "own_kagent_name",
    label: "Собственный",
    align: "left",
    field: "own_kagent_name",
  },
  {
    name: "tm_kagent_name",
    label: "Торг.сеть",
    align: "left",
    field: "tm_kagent_name",
  },
  {
    name: "fr_kagent_name",
    label: "Франчайзи",
    align: "left",
    field: "fr_kagent_name",
  },
  {
    name: "description",
    label: "Описание",
    align: "left",
    field: "description",
  },
  {
    name: "user_email",
    label: "EMail",
    align: "left",
    field: "user_email",
  },
  {
    name: "user_date",
    label: "Дата ред.",
    align: "left",
    field: "user_date",
  },
];
