export const columnsVisible = [
  "user_email",
  "user_date",
  "region_name",
  "address",
  "dateopen",
  "dateclose",
  "area",
  "kolbakers",
  "description",
  "territory_name",
];
export const columns = [
  {
    name: "name",
    label: "Сотрудник",
    align: "left",
    field: "name",
    required: true,
    sortable: true,
  },
  {
    name: "region_count",
    label: "Регионы",
    align: "left",
    field: "region_count",
    required: true,
    sortable: true,
  },
  {
    name: "territory_count",
    label: "Территории",
    align: "left",
    field: "territory_count",
    required: true,
    sortable: true,
  },
  {
    name: "bakery_count",
    label: "Пекарни",
    align: "left",
    field: "bakery_count",
    required: true,
    sortable: true,
  },
  // {
  //   name: "bakery_count",
  //   label: "Пекарни",
  //   align: "left",
  //   field: "bakery_count",
  //   required: true,
  //   sortable: true,
  // },
];
