export const columns = [
  {
    name: "article",
    label: "Артикул",
    align: "left",
    field: "article",
    required: true, // нельзя выключить
    sortable: true,
  },

  {
    name: "hidden",
    label: "Скрыто",
    align: "center",
    field: "hidden",
    sortable: true,
    hidden: true,
  },
  {
    name: "count_sale",
    label: "Кол-во",
    align: "right",
    field: "count_sale",
    required: true, // нельзя выключить
    sortable: true,
    hidden: true,
  },
  {
    name: "tovar_name",
    label: "Товар",
    align: "left",
    field: "tovar_name",
    sortable: true,
  },
  {
    name: "cena",
    label: "Цена",
    align: "right",
    field: "cena",
    sortable: true,
    hidden: true,
  },
  {
    name: "productvid_name",
    label: "Продукт",
    align: "left",
    field: "productvid_name",
    sortable: true,
    hidden: true,
  },
  // {
  //   name: "bakery_name",
  //   label: "Пекарня",
  //   align: "left",
  //   field: "bakery_name",
  //   sortable: true,
  //   hidden: false,
  // },
  {
    name: "trademark_name",
    label: "Сеть",
    align: "left",
    field: "trademark_name",
    sortable: true,
    hidden: true,
  },
  {
    name: "date_start",
    label: "Дата док.",
    align: "left",
    field: "date_start",
    sortable: true,
    hidden: true,
  },
  {
    name: "price_docnum",
    label: "Номер док.",
    align: "left",
    field: "price_docnum",
    sortable: true,
    hidden: true,
  },
  /////
  // {
  //   name: "kagent_name",
  //   label: "Контрагент",
  //   align: "left",
  //   field: "kagent_name",
  //   sortable: true,
  //   hidden: false,
  // },
  // {
  //   name: "kagent_own_name",
  //   label: "Кагент свой",
  //   align: "left",
  //   field: "kagent_own_name",
  //   sortable: true,
  //   hidden: false,
  // },
  // {
  //   name: "kagent_franch_name",
  //   label: "франчайзи",
  //   align: "left",
  //   field: "kagent_franch_name",
  //   sortable: true,
  //   hidden: false,
  // },
];
