export const columns = [
  {
    name: "name",
    label: "Сотрудник",
    align: "left",
    field: "name",
    required: true,
    sortable: true,
  },
  {
    name: "region_count",
    label: "Регионы",
    align: "right",
    field: "region_count",
    required: true,
    sortable: true,
  },
  {
    name: "territory_count",
    label: "Территории",
    align: "right",
    field: "territory_count",
    required: true,
    sortable: true,
  },
  {
    name: "bakery_count",
    label: "Пекарни",
    align: "right",
    field: "bakery_count",
    required: true,
    sortable: true,
  },
  // {
  //   name: "bakery_count",
  //   label: "Пекарни",
  //   align: "left",
  //   field: "bakery_count",
  //   required: true,
  //   sortable: true,
  // },
];
